src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Account", mappedBy="project", orphanRemoval=true)
     */
    private $accounts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MonitoringTask", mappedBy="project", orphanRemoval=true)
     */
    private $monitoringTasks;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
        $this->monitoringTasks = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Account[]
     */
    public function getAccounts(): Collection
    {
        return $this->accounts;
    }

    public function addAccount(Account $account): self
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts[] = $account;
            $account->setProject($this);
        }

        return $this;
    }

    public function removeAccount(Account $account): self
    {
        if ($this->accounts->contains($account)) {
            $this->accounts->removeElement($account);
            // set the owning side to null (unless already changed)
            if ($account->getProject() === $this) {
                $account->setProject(null);
            }
        }

        return $this;
    }

    public function userHaveAccessToProject(User $user)
    {
        // @ToDO use voters

        if ($user->hasRole(User::ROLE_ADMIN) || $user->hasRole(User::ROLE_SUPER_ADMIN)) {
            return true;
        }

        foreach ($this->getAccounts() as $account) {
            if ($account->getUsers()->contains($user)) {
                return true;
            }
        }

        return false;
    }

    public function getTagList():array
    {
        $tags = [];

        foreach ($this->getAccounts() as $account) {
            if (!empty($account->getTag()) && !in_array($account->getTag(), $tags)) {
                $tags[] = $account->getTag();
            }
        }

        return $tags;
    }

    /**
     * @return Collection|MonitoringTask[]
     */
    public function getMonitoringTasks(): Collection
    {
        return $this->monitoringTasks;
    }

    public function addMonitoringTask(MonitoringTask $monitoringTask): self
    {
        if (!$this->monitoringTasks->contains($monitoringTask)) {
            $this->monitoringTasks[] = $monitoringTask;
            $monitoringTask->setProject($this);
        }

        return $this;
    }

    public function removeMonitoringTask(MonitoringTask $monitoringTask): self
    {
        if ($this->monitoringTasks->contains($monitoringTask)) {
            $this->monitoringTasks->removeElement($monitoringTask);
            // set the owning side to null (unless already changed)
            if ($monitoringTask->getProject() === $this) {
                $monitoringTask->setProject(null);
            }
        }

        return $this;
    }

    public function isMonitoringStatusOk()
    {
        foreach ($this->getMonitoringTasks() as $task) {
            if ($task->getIsReportSent()) {
                return false;
            }
        }

        return true;
    }

    public function getMonitoringStatusBadCount()
    {
        $i = 0;

        foreach ($this->getMonitoringTasks() as $task) {
            if ($task->getIsReportSent()) {
                $i++;
            }
        }

        return $i;
    }
}

src/Controller/HomepageController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\User;
use App\Repository\AccountRepository;
use App\Repository\MonitoringTaskRepository;
use App\Repository\ProjectRepository;
use App\Services\MonitoringService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class HomepageController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     * @param ProjectRepository $projectRepository
     * @return Response
     */
    public function index(ProjectRepository $projectRepository)
    {
        /** @var User $user */
        $user = $this->getUser();

        // @ToDO Use voters

        if ($user->hasRole(User::ROLE_ADMIN) || $user->hasRole(User::ROLE_SUPER_ADMIN)) {
            $projects = $projectRepository->findAllWithAccounts();
        } else {
            $projects = $projectRepository->findByUser($this->getUser());
        }

        if (!empty($projects)) {
            return $this->redirectToRoute('project_details', ['id' => $projects[0]->getId()]);
        }

        return $this->render('homepage/index.html.twig', [
            'projects' => $projects,
            'currentProject' => null
        ]);
    }

    /**
     * @Route("/project/{id}", name="project_details")
     * @param Project $project
     * @param ProjectRepository $projectRepository
     * @return Response
     */
    public function details(Project $project, ProjectRepository $projectRepository)
    {
        /** @var User $user */
        $user = $this->getUser();

        // @ToDO Use voters

        if (!$project->userHaveAccessToProject($user)) {
            throw new AccessDeniedException();
        }

        if ($user->hasRole(User::ROLE_ADMIN) || $user->hasRole(User::ROLE_SUPER_ADMIN)) {
            $projects = $projectRepository->findAllWithAccounts();
        } else {
            $projects = $projectRepository->findByUser($this->getUser());
        }

        return $this->render('homepage/index.html.twig', [
            'projects' => $projects,
            'currentProject' => $project
        ]);
    }
}

templates/homepage/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <!-- top tiles -->
    <div class="row" style="display: inline-block;" >
        <div class="tile_count">
            <div class="col-md-12 col-sm-12  tile_stats_count">
                <span class="count_top"><i class="fa fa-clock-o"></i>  Monitoring status</span>
                <div class="count {% if currentProject.isMonitoringStatusOk %}green{% else %}red{% endif %}">{% if currentProject.isMonitoringStatusOk %}OK{% else %}BROKEN{% endif %}
                    {% if currentProject.isMonitoringStatusOk %}
                        ({{ currentProject.monitoringTasks.count }} / {{ currentProject.monitoringTasks.count }})
                    {% else %}
                        ({{ currentProject.monitoringStatusBadCount }} / {{ currentProject.monitoringTasks.count }})
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- /top tiles -->
    <div class="row">
        <div class="col-md-12">
            {% for tag in currentProject.tagList %}
               <div class="x_panel">
                    <div class="x_title">
                        <h2>{{ tag }}</h2>
                        <div class="clearfix"></div>
                    </div>

                   <div class="x_content row">
                   {% for account in currentProject.accounts %}
                       {% if account.tag == tag %}
                                <div class="col-md-3 col-sm-12 ">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>{{ account.title }}</h2>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">
                                            <table class="table">
                                                <tbody>
                                                <tr>
                                                    <th scope="row">login</th>
                                                    <td style="word-break: break-all; white-space: pre-line;">{{account.login}}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">password</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.password}}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">link</th>
                                                    <td style="word-break: break-all; white-space: pre-line"><a href="{{ account.link }}">{{account.link}}</a></td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">extra data</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.extraData|raw}}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">description</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.description}}</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                   {% endif %}
                {% endfor %}
                   </div>
            </div>
            {% endfor %}
               <div class="x_panel">
                    <div class="x_title">
                        <h2>Another</h2>
                        <div class="clearfix"></div>
                    </div>

                   <div class="x_content row">
                   {% for account in currentProject.accounts %}
                       {% if account.tag is empty  %}
                                <div class="col-md-3 col-sm-12 ">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>{{ account.title }}</h2>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">
                                            <table class="table">
                                                <tbody>
                                                <tr>
                                                    <th scope="row">login</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.login}}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">password</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.password}}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">link</th>
                                                    <td style="word-break: break-all; white-space: pre-line"><a href="{{ account.link }}">{{account.link}}</a></td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">extra data</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.extraData}}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">description</th>
                                                    <td style="word-break: break-all; white-space: pre-line">{{account.description}}</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                   {% endif %}
                {% endfor %}
                   </div>
            </div>
        </div>
    </div>
{% endblock %}